var _neon=_neon||{},neonPageId=null,lastMouseClick,lastMouseClickElement;function _trackLastMouseClick(c){var a;c=c?c:event;c.srcElement?a=c.srcElement:c.target&&(a=c.target);lastMouseClickElement=a.localName;"object"==lastMouseClickElement&&(lastMouseClick=(new Date).getTime())}document.onmouseup=_trackLastMouseClick;Object.size=function(c){var a=0,l;for(l in c)c.hasOwnProperty(l)&&a++;return a};
(function(c){function a(){d=!1;for(var e in l){var a=c(l[e]).filter(function(){return c(this).is(":appeared")});a.trigger("appear",[a]);if(m){var b=m.not(a);b.trigger("disappear",[b])}m=a}}var l=[],f=!1,d=!1,p={interval:250,force_process:!1},g=c(window),m;c.expr[":"].appeared=function(e){e=c(e);if(!e.is(":visible"))return!1;var a=g.scrollLeft(),b=g.scrollTop(),k=e.offset(),n=k.left,k=k.top;return k+e.height()>=b&&k-(e.data("appear-top-offset")||0)<=b+g.height()&&n+e.width()>=a&&n-(e.data("appear-left-offset")||
0)<=a+g.width()?!0:!1};c.fn.extend({appear:function(e){var h=c.extend({},p,e||{});e=this.selector||this;if(!f){var b=function(){d||(d=!0,setTimeout(a,h.interval))};c(window).scroll(b).resize(b);f=!0}h.force_process&&setTimeout(a,h.interval);l.push(e);return c(e)}});c.extend({force_appear:function(){return f?(a(),!0):!1}})})(_neonjQuery);
(function(c){_neon.JsonRequester=function(){function a(c){this.fullUrl=c;this.noCacheIE="&noCacheIE="+(new Date).getTime();this.headLoc=document.getElementsByTagName("head").item(0);this.scriptId="JscriptId"+a.scriptCounter++}a.scriptCounter=1;a.prototype.buildScriptTag=function(){this.scriptObj=document.createElement("script");this.scriptObj.setAttribute("type","text/javascript");this.scriptObj.setAttribute("charset","utf-8");this.scriptObj.setAttribute("src",this.fullUrl+this.noCacheIE);this.scriptObj.setAttribute("id",
this.scriptId)};a.prototype.removeScriptTag=function(){this.headLoc.removeChild(this.scriptObj)};a.prototype.addScriptTag=function(){this.headLoc.appendChild(this.scriptObj)};return{sendRequest:function(c){try{bObj=new a(c),bObj.buildScriptTag(),bObj.addScriptTag()}catch(f){}}}}();_neon.utils={getRandomString:function(a){return parseInt(1E8*(1+Math.random()),10).toString().substr(0,a)},isHidden:function(a){return null===a.offsetParent?!0:!1},isAnchor:function(a){return"A"==a.prop("tagName")},sameSiteReferral:function(){var a=
document.referrer;-1!==a.indexOf("http://")?a=a.substr(7):-1!==a.indexOf("https://")&&(a=a.substr(8));return a==window.location.hostname},getPageRequestUUID:function(){for(var a="",c=16;0<c;--c)a+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"[Math.round(61*Math.random())];return a},isOnScreen:function(a){a=c(a);var l=c(window),f=l.scrollTop(),d=l.scrollLeft(),p;p=d+l.width();var l=f+l.height(),g=a.offset();g.right=g.left+a.outerWidth();g.bottom=g.top+a.outerHeight();return!(p<g.left||
d>g.right||l<g.top||f>g.bottom)},getBackgroundImageUrl:function(a){a=c(a).css("background-image");a=a.replace("url(","").replace(")","");return a.substr(7)},getQueryValue:function(a,c){for(var f=a&&a.substring(1).split("&"),d=0,p=f.length;d<p;d++){var g=f[d],m=g.indexOf("=");if((g&&g.substring(0,m))===c)return g.substring(m+1,g.length)}}};_neon.tracker=function(){function a(){for(var b=document.getElementsByTagName("div"),a=b.length,e,c=[],h=0;h<a;h++)e=b[h],e.currentStyle?"none"!==e.currentStyle.backgroundImage&&
c.push(e):window.getComputedStyle&&"none"!==document.defaultView.getComputedStyle(e,null).getPropertyValue("background-image")&&c.push(e);return c}function l(b){lastMouseClick=(new Date).getTime();var a=c(this).offset(),n=c(this).attr("src"),h=a.left,a=a.top,n=e[n];"undefined"!==typeof n&&_neon.TrackerEvents.sendImageClickEvent(n[0],n[1],h,a,b.pageX,b.pageY)}function f(){var b=[],k={};c("img").each(function(){c(this);var a=c(this).attr("src");-1<a.indexOf("neontn")&&(b.push(a),c(this).click(l),k[a]=
[c(this).width(),c(this).height()])});h=a();for(var n=0;n<h.length;n++){var s=_neon.utils.getBackgroundImageUrl(h[n]);b.push(s);k[s]=[c(this).width(),c(this).height()]}e=g(b);_neon.TrackerEvents.sendImagesLoadedEvent(e,k);p(b)}function d(){c(window).bind("load",function(){f()})}function p(b){c("img").appear();for(var a={},n={},g=[],l=0;l<b.length;l++){var d=c('img[src$="'+b[l]+'"]');g.push(d);a[b[l]]=0;n[b[l]]=0}var m={};setInterval(function(){for(var b={},c=!1,l=0;l<g.length;l++){var d=g[l];d.is(":appeared")&&
(d=d.attr("src"),e.hasOwnProperty(d)&&(vidId=e[d][0],thumbId=e[d][1],m.hasOwnProperty(d)||(a[d]=1,_neon.StorageModule.storeThumbnail(vidId,thumbId)),b[d]=1,c=!0))}for(l=0;l<h.length;l++)d=h[l],_neon.utils.isOnScreen(d)&&(d=_neon.utils.getBackgroundImageUrl(d),e.hasOwnProperty(d)&&(vidId=e[d][0],thumbId=e[d][1],m.hasOwnProperty(d)||(a[d]=1,_neon.StorageModule.storeThumbnail(vidId,thumbId)),b[d]=1,c=!0));if(c){m=b;var b=[],f;for(f in a)1===a[f]&&0==n[f]&&(n[f]=1,b.push(e[f]));0<b.length&&_neon.TrackerEvents.sendImagesVisibleEvent(b)}},
1E3);c(window).bind("beforeunload",function(){_neon.StorageModule.getAllThumbnails("session")})}function g(b){for(var a={},e=0;e<b.length;e++){var c=m(b[e]);c&&(a[b[e]]=c)}return a}function m(b){return-1<b.indexOf("neontn")?(b=b.split("neontn")[1].split(".jpg")[0],[b.split("-")[1],b]):null}var e,h;return{init:function(){d()},getTrackerAccountId:function(){for(var b=document.getElementsByTagName("script"),a=0;a<b.length;a++)if(sTag=b[a],0<=sTag.src.search("neonbootloader")||0<=sTag.src.search("neonbctracker.js"))return sTag.id},
getTrackerType:function(){return"brightcove"},getLastClickNeonElementTS:function(){return lastMouseClick},getLastClickNeonElement:function(){return lastMouseClickElement},setLastClickNeonElement:function(a){lastMouseClick=(new Date).getTime();lastMouseClickElement=a},mapImagesToTids:f,parseNeonBrightcoveUrl:m}}();_neon.StorageModule=function(){function a(a){return a.match(/:\/\/(www[0-9]?\.)?(.[^/:]+)/)[2]}function c(a,h){"undefined"===typeof h&&(h=g);if("undefined"===typeof a){var b=document.URL.split("?")[0];
return h+m+b}return h+m+a}function f(a,h,b){var k=parseInt((new Date).getTime()/1E3,10);storageKey=a==localStorage?g:c();var d=JSON.parse(a.getItem(storageKey));d||(d={});d[h]={thumbId:b,ts:k};a.setItem(storageKey,JSON.stringify(d))}function d(a,c,b){return(a=JSON.parse(a.getItem(c)))?a[b]:!1}function p(a){return ret=d(localStorage,g,a)}var g="neonThumbnails",m="+";return{getUid:function(){var a=localStorage.getItem("uid");a||(a=(new Date).getTime(),a=_neon.utils.getRandomString(4)+_neon.utils.getRandomString(4)+
a.toString().substring(11,13),localStorage.setItem("uid",a));return a},storeThumbnail:function(a,c){f(sessionStorage,a,c);f(localStorage,a,c)},getThumbnail:function(e,h){var b="session",k=c(h);if(k=d(sessionStorage,k,e))return[k,b];if(h&&a(document.URL)!=a(h))return null;k=p(e);_neon.TrackerEvents.sendImageClickEvent(e,k?k[0].thumbId:null);return k?[k,"local"]:null},getThumbnailSessionStorage:function(a,h){var b=c(h);return d(sessionStorage,b,a)},getThumbnailLocalStorage:function(a){return p(a)},
getAllThumbnails:function(a){if("session"==a){a=RegExp(g);for(var c=0;c<sessionStorage.length;c++){var b=sessionStorage.key(c);if(a.test(b))return sessionStorage.getItem(b)}return null}return JSON.parse(localStorage.getItem(g))},clearPageSessionData:function(a){if("undefined"===typeof a){a=document.URL.split("?")[0];a=c(a);for(var d=0;d<sessionStorage.length;d++){var b=sessionStorage.key(d);b==a&&sessionStorage.removeItem(b)}}}}}();_neon.TrackerEvents=function(){function a(){d=_neon.tracker.getTrackerAccountId();
p=_neon.tracker.getTrackerType();g=document.URL.split("?")[0];m=document.referrer.split("?")[0];e=(new Date).getTime();return"http://trackserver-test-691751517.us-east-1.elb.amazonaws.com/v2/track?a="+h+"&page="+encodeURIComponent(g)+"&pageid="+f+"&ttype="+p+"&ref="+encodeURIComponent(m)+"&tai="+d+"&cts="+e}function c(a,d){var e=[],h;for(h in a)a[h]&&(tid=a[h][1],"undefined"!==typeof d&&(tid+="+"+d[h][0]+"+"+d[h][1]),e.push(tid));return e}var f=_neon.utils.getPageRequestUUID(),d,p,g,m,e,h;return{sendImageClickEvent:function(b,
c,d,e,g,l){h="ic";var f=a(),f=f+("&vid="+b+"&tid="+c);"undefined"!==typeof d&&"undefined"!==typeof e&&"undefined"!==typeof g&&"undefined"!==typeof l&&(f+="&wx="+d+"&wy="+e+"&x="+g+"&y="+l);_neon.JsonRequester.sendRequest(f)},sendVideoPlayEvent:function(b,c,d,e,g,l){h="vp";var f=a(),f=f+("&vid="+b+"&tid="+c+"&adPlay="+e+"&adelta="+g+"&pcount="+l);"undefined"!==typeof d&&(f+="&playerid="+d);_neon.JsonRequester.sendRequest(f)},sendAdPlayEvent:function(b,c,d,e,g){h="ap";var f=a(),f=f+("&vid="+b+"&tid="+
c+"&adelta="+e+"&pcount="+g);"undefined"!==typeof d&&(f+="&playerid="+d);_neon.JsonRequester.sendRequest(f)},sendImagesVisibleEvent:function(b){h="iv";b=c(b);var d=a();_neon.JsonRequester.sendRequest(d+("&tids="+b))},sendImagesLoadedEvent:function(b,d){h="il";var e=c(b,d),f=a();_neon.JsonRequester.sendRequest(f+("&tids="+e))},sendVideoClickEvent:function(b,c,d){h="vc";var e=a();_neon.JsonRequester.sendRequest(e+("&vid="+b+"&tid="+c+"&playerid="+d))},setPageLoadId:function(a){f=a}}}();_neon.BCNeonPlayerTracker=
function(){function a(a,b){b=b.split("?")[0];var c=_neon.tracker.parseNeonBrightcoveUrl(b);null!=c&&(r[b]=c,a=c[0],c=c[1],w[a]=[c,"player"],_neon.StorageModule.storeThumbnail(a,c))}function c(a){var b=document.referrer.split("?")[0],d=null,e=null,f;f=v&&2E3>=v?!1:!0;if(f){if(1==t&&""!=b){if(a=_neon.StorageModule.getThumbnail(a,b))d=a[0].thumbId,e=a[1];return[d,e]}return w[a]}if("object"==_neon.tracker.getLastClickNeonElement())return w[a];if(a=_neon.StorageModule.getThumbnail(a))return d=a[0].thumbId,
e=a[1],[d,e]}function f(){var a={},b=s.getAllMediaCollections();if(0<b.length&&0<b[0].mediaCount){for(var c=0;c<b[0].mediaCount;c++)if(url=s.getMedia(b[0].mediaIds[c]).thumbnailURL,null!=url){url=url.split("?")[0];a[url]=[120,90];var d=_neon.tracker.parseNeonBrightcoveUrl(url);if(null!=d){r[url]=d;var e=d[0],d=d[1];w[e]=[d,"player"];_neon.StorageModule.storeThumbnail(e,d)}}0<Object.size(r)&&(_neon.TrackerEvents.sendImagesVisibleEvent(r),_neon.TrackerEvents.sendImagesLoadedEvent(r,a))}}function d(a){!1==
y&&(t+=1);vid=a.media.id;a=c(vid);var b=null,d=null;null!=a&&(b=a[0],d=a[1],"local"==d&&_neon.TrackerEvents.sendImageClickEvent(vid,b));_neon.TrackerEvents.sendVideoPlayEvent(vid,b,n,y,v,t);!0==A&&_neon.TrackerEvents.sendAdPlayEvent(vid,b,n,v,t)}function p(a){if(z){z=!1;var b=_neon.tracker.getLastClickNeonElementTS();b&&(v=B-b);x=a=a.media.id;var b=w[a],c=null;b&&(c=b[0]);_neon.TrackerEvents.sendVideoClickEvent(a,c,n)}}function g(a){A=null==x?!0:!1;y=!0;(new Date).getTime();t+=1;if(!1==A){a=c(x);
var b=null;a&&(b=a[0]);_neon.TrackerEvents.sendAdPlayEvent(x,b,n,v,t)}}function m(a){B=(new Date).getTime();z=!0;y=!1;x=a.media.id}function e(a){a=a.split(",");for(var b=0;b<a.length;b++)playlist=a[b],s.getPlaylistByID(playlist,h)}function h(a){var b={};a=a.videos;for(var c=0;c<a.length;c++)if(url=a[c].thumbnailURL,null!=url){url=url.split("?")[0];b[url]=[120,90];var d=_neon.tracker.parseNeonBrightcoveUrl(url);if(null!=d){r[url]=d;var e=d[0],d=d[1];w[e]=[d,"player"];_neon.StorageModule.storeThumbnail(e,
d)}}0<Object.size(r)&&(_neon.TrackerEvents.sendImagesVisibleEvent(r),_neon.TrackerEvents.sendImagesLoadedEvent(r,b))}var b=null,k,n=null,s,q,u,x=null,B=null,z=!0,t=0,y=!1,v=null,A=!1,r={},w={};return{onTemplateReady:function(c){c.target.experience?(APIModules=brightcove.api.modules.APIModules,b?(k=b.getModule(APIModules.VIDEO_PLAYER),s=b.getModule(APIModules.CONTENT),q=b.getModule(APIModules.EXPERIENCE),k.addEventListener(brightcove.api.events.MediaEvent.BEGIN,d),k.addEventListener(brightcove.api.events.MediaEvent.PLAY,
p),k.addEventListener(brightcove.api.events.MediaEvent.CHANGE,m),k.addEventListener(brightcove.api.events.MediaEvent.COMPLETE,m),b.getModule(APIModules.ADVERTISING).addEventListener(brightcove.api.events.AdEvent.START,g),k.getCurrentVideo(function(b){u=b;a(u.id,u.thumbnailURL)}),q.getExperienceID(function(a){n=a}),playerHtmlObject=document.getElementById(b.id),playlists=_neon.utils.getQueryValue(playerHtmlObject.data.split("?")[1],"%40playlistTabs"),e(playlists)):(APIModules=brightcove.api.modules.APIModules,
q=c.target.experience.getModule(APIModules.EXPERIENCE),q.getExperienceID(function(a){n=a;k=q.experience.getModule(APIModules.VIDEO_PLAYER);k.addEventListener(brightcove.api.events.MediaEvent.BEGIN,d);k.addEventListener(brightcove.api.events.MediaEvent.PLAY,p);k.addEventListener(brightcove.api.events.MediaEvent.CHANGE,m);k.addEventListener(brightcove.api.events.MediaEvent.COMPLETE,m);q.experience.getModule(APIModules.ADVERTISING).addEventListener(brightcove.api.events.AdEvent.START,g)}))):(u=k.getCurrentVideo(),
a(u.id,u.thumbnailURL))},onTemplateLoad:function(a){try{b=brightcove.api.getExperience(a)}catch(c){}null==b&&(b=bcPlayer.getPlayer(a),k=b.getModule(APIModules.VIDEO_PLAYER),q=b.getModule(APIModules.EXPERIENCE),n=q.getExperienceID(),s=b.getModule(APIModules.CONTENT),k.addEventListener(BCMediaEvent.BEGIN,d),k.addEventListener(BCMediaEvent.PLAY,p),k.addEventListener(BCMediaEvent.COMPLETE,m),k.addEventListener(BCMediaEvent.CHANGE,m),q.addEventListener(BCExperienceEvent.CONTENT_LOAD,f),advertising=b.getModule(APIModules.ADVERTISING),
advertising.addEventListener(BCAdvertisingEvent.AD_START,g))}}}();(function(){function a(){if("complete"===document.readyState||"interactive"===document.readyState)_neon.StorageModule.clearPageSessionData(),clearInterval(l),c(document).bind("touchstart",function(a){lastMouseClick=(new Date).getTime()}),NeonPlayerTracker=_neon.BCNeonPlayerTracker}if(!_neon.UNITTEST){var l=setInterval(a,100);sessionStorage&&localStorage&&JSON&&_neon.tracker.init()}})()})(_neonjQuery);
