var _neon=_neon||{},neonPageId=null,lastMouseClick,lastMouseClickElement;function _trackLastMouseClick(c){var a;c=c?c:event;c.srcElement?a=c.srcElement:c.target&&(a=c.target);lastMouseClickElement=a.localName;"object"==lastMouseClickElement&&(lastMouseClick=(new Date).getTime())}document.onmouseup=_trackLastMouseClick;Object.size=function(c){var a=0,h;for(h in c)c.hasOwnProperty(h)&&a++;return a};
(function(c){function a(){e=!1;for(var f in h){var d=c(h[f]).filter(function(){return c(this).is(":appeared")});d.trigger("appear",[d]);if(n){var b=n.not(d);b.trigger("disappear",[b])}n=d}}var h=[],k=!1,e=!1,m={interval:250,force_process:!1},g=c(window),n;c.expr[":"].appeared=function(f){f=c(f);if(!f.is(":visible"))return!1;var d=g.scrollLeft(),b=g.scrollTop(),l=f.offset(),a=l.left,l=l.top;return l+f.height()>=b&&l-(f.data("appear-top-offset")||0)<=b+g.height()&&a+f.width()>=d&&a-(f.data("appear-left-offset")||
0)<=d+g.width()?!0:!1};c.fn.extend({appear:function(f){var d=c.extend({},m,f||{});f=this.selector||this;if(!k){var b=function(){e||(e=!0,setTimeout(a,d.interval))};c(window).scroll(b).resize(b);k=!0}d.force_process&&setTimeout(a,d.interval);h.push(f);return c(f)}});c.extend({force_appear:function(){return k?(a(),!0):!1}})})(_neonjQuery);
(function(c){_neon.JsonRequester=function(){function a(c){this.fullUrl=c;this.noCacheIE="&noCacheIE="+(new Date).getTime();this.headLoc=document.getElementsByTagName("head").item(0);this.scriptId="JscriptId"+a.scriptCounter++}a.scriptCounter=1;a.prototype.buildScriptTag=function(){this.scriptObj=document.createElement("script");this.scriptObj.setAttribute("type","text/javascript");this.scriptObj.setAttribute("charset","utf-8");this.scriptObj.setAttribute("src",this.fullUrl+this.noCacheIE);this.scriptObj.setAttribute("id",
this.scriptId)};a.prototype.removeScriptTag=function(){this.headLoc.removeChild(this.scriptObj)};a.prototype.addScriptTag=function(){this.headLoc.appendChild(this.scriptObj)};return{sendRequest:function(c){try{bObj=new a(c),bObj.buildScriptTag(),bObj.addScriptTag()}catch(k){}}}}();_neon.utils={getRandomString:function(a){return parseInt(1E8*(1+Math.random()),10).toString().substr(0,a)},isHidden:function(a){return null===a.offsetParent?!0:!1},isAnchor:function(a){return"A"==a.prop("tagName")},sameSiteReferral:function(){var a=
document.referrer;-1!==a.indexOf("http://")?a=a.substr(7):-1!==a.indexOf("https://")&&(a=a.substr(8));return a==window.location.hostname},getPageRequestUUID:function(){for(var a="",c=16;0<c;--c)a+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"[Math.round(61*Math.random())];return a},isOnScreen:function(a){a=c(a);var h=c(window),k=h.scrollTop(),e=h.scrollLeft(),m;m=e+h.width();var h=k+h.height(),g=a.offset();g.right=g.left+a.outerWidth();g.bottom=g.top+a.outerHeight();return!(m<g.left||
e>g.right||h<g.top||k>g.bottom)},getBackgroundImageUrl:function(a){a=c(a).css("background-image");a=a.replace("url(","").replace(")","");return a.substr(7)},getQueryValue:function(a,c){for(var k=a&&a.substring(1).split("&"),e=0,m=k.length;e<m;e++){var g=k[e],n=g.indexOf("=");if((g&&g.substring(0,n))===c)return g.substring(n+1,g.length)}}};_neon.tracker=function(){function a(){for(var b=document.getElementsByTagName("div"),f=b.length,a,d=[],c=0;c<f;c++)a=b[c],a.currentStyle?"none"!==a.currentStyle.backgroundImage&&
d.push(a):window.getComputedStyle&&"none"!==document.defaultView.getComputedStyle(a,null).getPropertyValue("background-image")&&d.push(a);return d}function h(b){lastMouseClick=(new Date).getTime();var a=b.data.imgsrc,d=c(this).offset(),g=d.left-c(window).scrollLeft(),q=d.top-c(window).scrollTop(),h=d.left,d=d.top,a=f[a];"undefined"!==typeof a&&_neon.TrackerEvents.sendImageClickEvent(a[0],a[1],g,q,h,d,b.clientX,b.clientY)}function k(){var b=[],l={};c("img").each(function(){c(this);var a=c(this).attr("src");
if(-1<a.indexOf("neontn")){b.push(a);var f=c(this);$parent=f.parent();try{f.click({imgsrc:f.attr("src")},h),_neon.utils.isAnchor($parent)&&0>$parent.attr("href").indexOf("http://")&&$parent.click({imgsrc:f.attr("src")},h)}catch(d){console.log(d)}l[a]=[c(this).width(),c(this).height()]}});d=a();for(var p=0;p<d.length;p++){var e=_neon.utils.getBackgroundImageUrl(d[p]);b.push(e);l[e]=[c(this).width(),c(this).height()]}f=g(b);_neon.TrackerEvents.sendImagesLoadedEvent(f,l);m(b)}function e(){c(window).bind("load",
function(){k()})}function m(b){c("img").appear();for(var a={},p={},g=[],h=0;h<b.length;h++){var e=c('img[src$="'+b[h]+'"]');g.push(e);a[b[h]]=0;p[b[h]]=0}var k={};setInterval(function(){for(var b={},c=!1,h=0;h<g.length;h++){var e=g[h];e.is(":appeared")&&(e=e.attr("src"),f.hasOwnProperty(e)&&(vidId=f[e][0],thumbId=f[e][1],k.hasOwnProperty(e)||(a[e]=1,_neon.StorageModule.storeThumbnail(vidId,thumbId)),b[e]=1,c=!0))}for(h=0;h<d.length;h++)e=d[h],_neon.utils.isOnScreen(e)&&(e=_neon.utils.getBackgroundImageUrl(e),
f.hasOwnProperty(e)&&(vidId=f[e][0],thumbId=f[e][1],k.hasOwnProperty(e)||(a[e]=1,_neon.StorageModule.storeThumbnail(vidId,thumbId)),b[e]=1,c=!0));if(c){k=b;var b=[],q;for(q in a)1===a[q]&&0==p[q]&&(p[q]=1,b.push(f[q]));0<b.length&&_neon.TrackerEvents.sendImagesVisibleEvent(b)}},1E3);c(window).bind("beforeunload",function(){_neon.StorageModule.getAllThumbnails("session")})}function g(b){for(var a={},f=0;f<b.length;f++){var d=n(b[f]);d&&(a[b[f]]=d)}return a}function n(b){return-1<b.indexOf("neontn")?
(b=b.split("neontn")[1].split(".jpg")[0],[b.split("-")[1],b]):null}var f,d;return{init:function(){e()},getTrackerAccountId:function(){for(var b=document.getElementsByTagName("script"),a=0;a<b.length;a++){sTag=b[a];if(0<=sTag.src.search("neonbootloader")||0<=sTag.src.search("neonbctracker.js"))return sTag.id;if(0<=sTag.src.search("neonoptimizer"))return sTag.src.split("_")[1].split(".js")[0]}},getTrackerType:function(){return"brightcove"},getLastClickNeonElementTS:function(){return lastMouseClick},
getLastClickNeonElement:function(){return lastMouseClickElement},setLastClickNeonElement:function(a){lastMouseClick=(new Date).getTime();lastMouseClickElement=a},mapImagesToTids:k,parseNeonBrightcoveUrl:n}}();_neon.StorageModule=function(){function a(a){return a.match(/:\/\/(www[0-9]?\.)?(.[^/:]+)/)[2]}function c(a,d){"undefined"===typeof d&&(d=g);if("undefined"===typeof a){var b=document.URL.split("?")[0];return d+n+b}return d+n+a}function k(a,d,b){var e=parseInt((new Date).getTime()/1E3,10);storageKey=
a==localStorage?g:c();var p=JSON.parse(a.getItem(storageKey));p||(p={});p[d]={thumbId:b,ts:e};a.setItem(storageKey,JSON.stringify(p))}function e(a,d,b){return(a=JSON.parse(a.getItem(d)))?a[b]:!1}function m(a){return ret=e(localStorage,g,a)}var g="neonThumbnails",n="+";return{getUid:function(){var a=localStorage.getItem("uid");a||(a=(new Date).getTime(),a=_neon.utils.getRandomString(4)+_neon.utils.getRandomString(4)+a.toString().substring(11,13),localStorage.setItem("uid",a));return a},storeThumbnail:function(a,
d){k(sessionStorage,a,d);k(localStorage,a,d)},getThumbnail:function(f,d){var b="session",l=c(d);return(l=e(sessionStorage,l,f))?[l,b]:d&&a(document.URL)!=a(d)?null:(l=m(f))?[l,"local"]:null},getThumbnailSessionStorage:function(a,d){var b=c(d);return e(sessionStorage,b,a)},getThumbnailLocalStorage:function(a){return m(a)},getAllThumbnails:function(a){if("session"==a){a=new RegExp(g);for(var d=0;d<sessionStorage.length;d++){var b=sessionStorage.key(d);if(a.test(b))return sessionStorage.getItem(b)}return null}return JSON.parse(localStorage.getItem(g))},
clearPageSessionData:function(a){if("undefined"===typeof a){a=document.URL.split("?")[0];a=c(a);for(var d=0;d<sessionStorage.length;d++){var b=sessionStorage.key(d);b==a&&sessionStorage.removeItem(b)}}}}}();_neon.TrackerEvents=function(){function a(a){e=_neon.tracker.getTrackerAccountId();m=_neon.tracker.getTrackerType();g=document.URL.split("?")[0];n=document.referrer.split("?")[0];var b=(new Date).getTime();"undefined"!==typeof a&&(b=a);return"http://trackserver-test-691751517.us-east-1.elb.amazonaws.com/v2/track?a="+
f+"&page="+encodeURIComponent(g)+"&pageid="+k+"&ttype="+m+"&ref="+encodeURIComponent(n)+"&tai="+e+"&cts="+b}function c(a,b){var f=[],e;for(e in a)a[e]&&(tid=a[e][1],"undefined"!==typeof b&&(tid+="+"+b[e][0]+"+"+b[e][1]),f.push(tid));return f}var k=_neon.utils.getPageRequestUUID(),e,m,g,n,f;return{sendImageClickEvent:function(d,b,c,e,g,h,k,n){f="ic";var m=a(),m=m+("&vid="+d+"&tid="+b);"undefined"!==typeof c&&"undefined"!==typeof e&&"undefined"!==typeof g&&"undefined"!==typeof h&&"undefined"!==typeof k&&
(m+="&wx="+c+"&wy="+e+"&x="+g+"&y="+h+"&cx="+k+"&cy="+n);_neon.JsonRequester.sendRequest(m)},sendVideoPlayEvent:function(d,b,c,e,g,h){f="vp";var k=a(),k=k+("&vid="+d+"&tid="+b+"&adPlay="+e+"&adelta="+g+"&pcount="+h);"undefined"!==typeof c&&(k+="&playerid="+c);_neon.JsonRequester.sendRequest(k)},sendAdPlayEvent:function(d,b,c,e,g,h){f="ap";h=a(h);h+="&vid="+d+"&tid="+b+"&adelta="+e+"&pcount="+g;"undefined"!==typeof c&&(h+="&playerid="+c);_neon.JsonRequester.sendRequest(h)},sendImagesVisibleEvent:function(d){f=
"iv";d=c(d);var b=a();_neon.JsonRequester.sendRequest(b+("&tids="+d))},sendImagesLoadedEvent:function(d,b){f="il";var e=c(d,b),g=a();_neon.JsonRequester.sendRequest(g+("&tids="+e))},sendVideoClickEvent:function(d,b,c){f="vc";var e=a();_neon.JsonRequester.sendRequest(e+("&vid="+d+"&tid="+b+"&playerid="+c))},setPageLoadId:function(a){k=a}}}();_neon.BCNeonPlayerTracker=function(){function a(a,b){b=b.split("?")[0];var c=_neon.tracker.parseNeonBrightcoveUrl(b);null!=c&&(r[b]=c,a=c[0],c=c[1],u[a]=[c,"player"],
_neon.StorageModule.storeThumbnail(a,c))}function c(a){var b=document.referrer.split("?")[0],d=null,e=null,f;f=t&&2E3>=t?!1:!0;if(f){if(1==s&&""!=b){if(a=_neon.StorageModule.getThumbnail(a,b))d=a[0].thumbId,e=a[1];return[d,e]}return u[a]}if("object"==_neon.tracker.getLastClickNeonElement())return u[a];if(a=_neon.StorageModule.getThumbnail(a))return d=a[0].thumbId,e=a[1],[d,e]}function k(){var a={},b=x.getAllMediaCollections();if(0<b.length&&0<b[0].mediaCount){for(var c=0;c<b[0].mediaCount;c++)if(url=
x.getMedia(b[0].mediaIds[c]).thumbnailURL,null!=url){url=url.split("?")[0];a[url]=[120,90];var d=_neon.tracker.parseNeonBrightcoveUrl(url);if(null!=d){r[url]=d;var e=d[0],d=d[1];u[e]=[d,"player"];_neon.StorageModule.storeThumbnail(e,d)}}0<Object.size(r)&&(_neon.TrackerEvents.sendImagesVisibleEvent(r),_neon.TrackerEvents.sendImagesLoadedEvent(r,a))}}function e(a){!1==z&&(s+=1);vid=a.media.id;a=c(vid);var b=null,d=null;null!=a&&(b=a[0],d=a[1],"local"==d&&_neon.TrackerEvents.sendImageClickEvent(vid,
b));_neon.TrackerEvents.sendVideoPlayEvent(vid,b,p,z,t,s);!0==B&&_neon.TrackerEvents.sendAdPlayEvent(vid,b,p,t,s,C)}function m(a){y=(new Date).getTime();if(A){A=!1;var b=_neon.tracker.getLastClickNeonElementTS();null==t&&b&&(t=y-b);w=a=a.media.id;var b=u[a],c=null;b&&(c=b[0]);_neon.TrackerEvents.sendVideoClickEvent(a,c,p)}}function g(a){B=null==w?!0:!1;z=!0;C=(new Date).getTime();s+=1;if(!1==B){a=c(w);var b=null;a&&(b=a[0]);_neon.TrackerEvents.sendAdPlayEvent(w,b,p,t,s)}}function n(a){y=(new Date).getTime();
A=!0;z=!1;w=a.media.id;var b=_neon.tracker.getLastClickNeonElementTS();b&&(t=y-b);w=a=a.media.id;var b=u[a],c=null;b&&(c=b[0]);_neon.TrackerEvents.sendVideoClickEvent(a,c,p)}function f(a){a=a.split(",");for(var b=0;b<a.length;b++)playlist=a[b],x.getPlaylistByID(playlist,d)}function d(a){var b={};a=a.videos;for(var c=0;c<a.length;c++)if(url=a[c].thumbnailURL,null!=url){url=url.split("?")[0];b[url]=[120,90];var d=_neon.tracker.parseNeonBrightcoveUrl(url);if(null!=d){r[url]=d;var e=d[0],d=d[1];u[e]=
[d,"player"];_neon.StorageModule.storeThumbnail(e,d)}}0<Object.size(r)&&(_neon.TrackerEvents.sendImagesVisibleEvent(r),_neon.TrackerEvents.sendImagesLoadedEvent(r,b))}var b=null,l,p=null,x,q,v,w=null,C=null,y=null,A=!0,s=0,z=!1,t=null,B=!1,r={},u={};return{onTemplateReady:function(c){c.target.experience?(APIModules=brightcove.api.modules.APIModules,b?(l=b.getModule(APIModules.VIDEO_PLAYER),x=b.getModule(APIModules.CONTENT),q=b.getModule(APIModules.EXPERIENCE),l.addEventListener(brightcove.api.events.MediaEvent.BEGIN,
e),l.addEventListener(brightcove.api.events.MediaEvent.PLAY,m),l.addEventListener(brightcove.api.events.MediaEvent.CHANGE,n),b.getModule(APIModules.ADVERTISING).addEventListener(brightcove.api.events.AdEvent.START,g),l.getCurrentVideo(function(b){v=b;a(v.id,v.thumbnailURL);0<Object.size(r)&&(_neon.TrackerEvents.sendImagesVisibleEvent(r),imgVisibleSizes={},imgVisibleSizes[Object.keys(r)[0]]=[120,90],_neon.TrackerEvents.sendImagesLoadedEvent(r,imgVisibleSizes))}),q.getExperienceID(function(a){p=a}),
playerHtmlObject=document.getElementById(b.id),playlists=_neon.utils.getQueryValue(playerHtmlObject.data.split("?")[1],"%40playlistTabs"),f(playlists)):(APIModules=brightcove.api.modules.APIModules,q=c.target.experience.getModule(APIModules.EXPERIENCE),q.getExperienceID(function(a){p=a;l=q.experience.getModule(APIModules.VIDEO_PLAYER);l.addEventListener(brightcove.api.events.MediaEvent.BEGIN,e);l.addEventListener(brightcove.api.events.MediaEvent.PLAY,m);l.addEventListener(brightcove.api.events.MediaEvent.CHANGE,
n);q.experience.getModule(APIModules.ADVERTISING).addEventListener(brightcove.api.events.AdEvent.START,g)}))):(v=l.getCurrentVideo(),a(v.id,v.thumbnailURL))},onTemplateLoad:function(a){try{b=brightcove.api.getExperience(a)}catch(c){}null==b&&(b=bcPlayer.getPlayer(a),l=b.getModule(APIModules.VIDEO_PLAYER),q=b.getModule(APIModules.EXPERIENCE),p=q.getExperienceID(),x=b.getModule(APIModules.CONTENT),l.addEventListener(BCMediaEvent.BEGIN,e),l.addEventListener(BCMediaEvent.PLAY,m),l.addEventListener(BCMediaEvent.CHANGE,
n),q.addEventListener(BCExperienceEvent.CONTENT_LOAD,k),advertising=b.getModule(APIModules.ADVERTISING),advertising.addEventListener(BCAdvertisingEvent.AD_START,g))}}}();(function(){function a(){if("complete"===document.readyState||"interactive"===document.readyState)_neon.StorageModule.clearPageSessionData(),clearInterval(h),c(document).bind("touchstart",function(a){lastMouseClick=(new Date).getTime()}),NeonPlayerTracker=_neon.BCNeonPlayerTracker}if(!_neon.UNITTEST){var h=setInterval(a,100);sessionStorage&&
localStorage&&JSON&&_neon.tracker.init()}})()})(_neonjQuery);
